# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/network_entropy',
                'doc_host': 'https://megaduks.github.io',
                'git_url': 'https://github.com/megaduks/network_entropy',
                'lib_path': 'network_entropy'},
  'syms': {'network_entropy.core': {'network_entropy.core.foo': ('core.html#foo', 'network_entropy/core.py')}}}
